-- AnimeEternalDelta.lua v8.0 - SECTORES AUTO FARM (Early/Mid/Late/Dungeon/Boss) OP!
local Plr=game.Players.LocalPlayer local WS=game.Workspace local RS=game.ReplicatedStorage local UIS=game:GetService("UserInputService") local VU=game:GetService("VirtualUser") local Mouse=Plr:GetMouse()
Plr.Idled:Connect(function()VU:CaptureController()VU:ClickButton2(Vector2.new())end)
local function GetRoot()return Plr.Character and Plr.Character:FindFirstChild("HumanoidRootPart")end local function GetHum()return Plr.Character and Plr.Character:FindFirstChild("Humanoid")end
print("AnimeEternalDelta v8 CARGADO! Sectores OP. 🔥")
local SG=Instance.new("ScreenGui")SG.Name="AEDelta"SG.Parent=Plr.PlayerGui SG.ResetOnSpawn=false SG.IgnoreGuiInset=true
local Frm=Instance.new("Frame")Frm.Size=UDim2.new(0.85,0,0.92,0)Frm.Position=UDim2.new(0.075,0,0.04,0)Frm.BackgroundColor3=Color3.fromRGB(20,20,25)Frm.BorderSizePixel=0 Frm.Active=true Frm.Draggable=true Frm.Parent=SG
local Tit=Instance.new("TextLabel")Tit.Size=UDim2.new(1,0,0,50)Tit.BackgroundColor3=Color3.fromRGB(255,100,0)Tit.Text="Anime Eternal v8 - AUTO SECTORES 🚀"Tit.TextColor3=Color3.new(1,1,1)Tit.TextScaled=true Tit.Font=Enum.Font.GothamBold Tit.Parent=Frm
local Min=Instance.new("TextButton")Min.Size=UDim2.new(0,40,0,40)Min.Position=UDim2.new(1,-95,0,5)Min.BackgroundColor3=Color3.fromRGB(255,200,0)Min.Text="-"Min.TextColor3=Color3.new(1,1,1)Min.Font=Enum.Font.GothamBold Min.TextScaled=true Min.Parent=Tit
local Cls=Instance.new("TextButton")Cls.Size=UDim2.new(0,40,0,40)Cls.Position=UDim2.new(1,-50,0,5)Cls.BackgroundColor3=Color3.fromRGB(255,50,50)Cls.Text="X"Cls.TextColor3=Color3.new(1,1,1)Cls.Font=Enum.Font.GothamBold Cls.TextScaled=true Cls.Parent=Tit
local minimized=false Min.Activated:Connect(function()minimized=not minimized Frm.Size=UDim2.new(0.85,0,minimized and 0.06 or 0.92,0)Frm.Position=UDim2.new(0.075,0,minimized and 0.94 or 0.04,0)Min.Text=minimized and"+"or"-"end)
local Togs={KillAura=false,AutoRoll=false,AutoStats=false,AutoSkills=false,AutoQuest=false,Speed=false,Noclip=false,AutoDungeon=false,AutoBoss=false}
local currentSector="None" -- Para sectors
local function Btn(ypos,text,cb,type) local B=Instance.new("TextButton")B.Size=UDim2.new(1,-20,0,45)B.Position=UDim2.new(0,10,ypos,60)B.BackgroundColor3=Color3.fromRGB(35,35,40)B.Text=text.." OFF" B.TextColor3=Color3.new(1,1,1)B.Font=Enum.Font.GothamBold B.TextScaled=true B.Parent=Frm
local tog=false B.Activated:Connect(function()tog=not tog B.BackgroundColor3=tog and Color3.fromRGB(0,255,100)or Color3.fromRGB(255,50,50)B.Text=text.." "..(tog and"ON"or"OFF") if type=="toggle"then cb(tog)else cb()end print(text..": "..tostring(tog))end)end
local function SectorBtn(ypos,sectorName,spawnCF) local B=Instance.new("TextButton")B.Size=UDim2.new(1,-20,0,45)B.Position=UDim2.new(0,10,ypos,60)B.BackgroundColor3=Color3.fromRGB(0,150,255)B.Text="TP & Farm "..sectorName B.TextColor3=Color3.new(1,1,1)B.Font=Enum.Font.GothamBold B.TextScaled=true B.Parent=Frm
B.Activated:Connect(function()currentSector=sectorName local Root=GetRoot()if Root then Root.CFrame=spawnCF Togs.KillAura=true print("TP "..sectorName.." + Aura ON")end end)end
-- GLOBALS TOGGLES
Btn(0,"Auto Roll Turbo",function(t)Togs.AutoRoll=t spawn(function()while Togs.AutoRoll do pcall(function()local keywords={"roll","spin","gacha","prize","star","banner"}local args={1,"Single",true,10}for _,r in pairs(RS:GetDescendants())do if r:IsA("RemoteEvent")and string.find(r.Name:lower(),table.concat(keywords,"|"))then for _,arg in pairs(args)do r:FireServer(arg)print("ROLL: "..r.Name)end end end end)wait(0.1)end end)end,"toggle")
Btn(0.07,"Auto Stats Max",function(t)Togs.AutoStats=t spawn(function()while Togs.AutoStats do pcall(function()local statsKw={"damage","energy","luck","stats"}for _,r in pairs(RS:GetDescendants())do if r:IsA("RemoteEvent")and string.find(r.Name:lower(),table.concat(statsKw,"|"))then r:FireServer("Damage",999);r:FireServer("Energy",999)end end end)wait(0.3)end end)end,"toggle")
Btn(0.14,"Auto Skills",function(t)Togs.AutoSkills=t spawn(function()while Togs.AutoSkills do pcall(function()Mouse:Click()for _,r in pairs(RS:GetDescendants())do if r:IsA("RemoteEvent")and string.find(r.Name:lower(),"skill")then for i=1,4 do r:FireServer(i)end end end end)wait(0.15)end end)end,"toggle")
Btn(0.21,"Auto Quest",function(t)Togs.AutoQuest=t spawn(function()while Togs.AutoQuest do pcall(function()for _,v in pairs(WS:GetDescendants())do if (v:IsA("ClickDetector")or v:IsA("ProximityPrompt"))and string.find(v.Parent.Name:lower(),"quest")or string.find(v.Parent.Name:lower(),"npc")then fireclickdetector(v);fireproximityprompt(v)end end end)wait(1)end end)end,"toggle")
Btn(0.28,"Speed x50",function(t)Togs.Speed=t local Hum=GetHum()if Hum then Hum.WalkSpeed=t and 100 or 16 end end,"toggle")
Btn(0.35,"Noclip",function(t)Togs.Noclip=t spawn(function()while Togs.Noclip do pcall(function()if Plr.Character then for _,p in pairs(Plr.Character:GetDescendants())do if p:IsA("BasePart")then p.CanCollide=false end end end end)wait()end end)end,"toggle")
-- KILL AURA GLOBAL (filtra por sector)
Btn(0.42,"Kill Aura Global",function(t)Togs.KillAura=t spawn(function()while Togs.KillAura do pcall(function()local Root=GetRoot()if Root then local closest=nil local minD=80 for _,obj in pairs(WS:GetDescendants())do if obj:IsA("Humanoid")and obj.Health>0 and obj.Parent~=Plr.Character and obj.Parent:FindFirstChild("HumanoidRootPart")then local dist=(Root.Position-obj.Parent.HumanoidRootPart.Position).Magnitude if dist<minD then minD=dist closest=obj.Parent.HumanoidRootPart end end end if closest then if minD>25 then Root.CFrame=closest.CFrame*CFrame.new(0,5,0) end -- Damage remotes for _,r in pairs(RS:GetDescendants())do if r:IsA("RemoteEvent")and string.find(r.Name:lower(),"damage|hit|combat|attack")then r:FireServer(closest)end end Mouse:Click()local Tool=Plr.Character:FindFirstChildOfClass("Tool")if Tool then Tool:Activate()end end end)wait(0.05)end end)end,"toggle")
-- SECTOR TP + FARM BUTTONS (divididos por areas)
SectorBtn(0.49,"Starter W1",CFrame.new(0,100,0)) -- Hub/Starter approx
SectorBtn(0.56,"Soul Forest W3",CFrame.new(400,100,400)) -- Approx from typical
SectorBtn(0.63,"Slayer W5",CFrame.new(800,100,800))
SectorBtn(0.70,"Desert Cairo W16",CFrame.new(-1200,100,1500))
SectorBtn(0.77,"Volcano Late",CFrame.new(2000,100,-1000))
-- SPECIAL
local DungeonBtn=Instance.new("TextButton")DungeonBtn.Size=UDim2.new(1,-20,0,45)DungeonBtn.Position=UDim2.new(0,10,0.84,60)DungeonBtn.BackgroundColor3=Color3.fromRGB(255,0,100)DungeonBtn.Text="Auto Dungeon" DungeonBtn.TextColor3=Color3.new(1,1,1)DungeonBtn.Font=Enum.Font.GothamBold DungeonBtn.TextScaled=true DungeonBtn.Parent=Frm
DungeonBtn.Activated:Connect(function()Togs.AutoDungeon=not Togs.AutoDungeon spawn(function()while Togs.AutoDungeon do pcall(function()-- Find enter for _,r in pairs(RS:GetDescendants())do if r:IsA("RemoteEvent")and string.find(r.Name:lower(),"dungeon|raid|enter")then r:FireServer("Enter")end end -- Prompts for _,v in pairs(WS:GetDescendants())do if v:IsA("ProximityPrompt")and string.find(v.Name:lower(),"dungeon")then fireproximityprompt(v)end end end)wait(5)-- Farm inside + reenter end end)print("Auto Dungeon: "..tostring(Togs.AutoDungeon))end)
local BossBtn=Instance.new("TextButton")BossBtn.Size=UDim2.new(1,-20,0,45)BossBtn.Position=UDim2.new(0,10,0.91,60)BossBtn.BackgroundColor3=Color3.fromRGB(200,0,255)BossBtn.Text="Auto Boss" BossBtn.TextColor3=Color3.new(1,1,1)BossBtn.Font=Enum.Font.GothamBold BossBtn.TextScaled=true BossBtn.Parent=Frm
BossBtn.Activated:Connect(function()Togs.AutoBoss=not Togs.AutoBoss spawn(function()while Togs.AutoBoss do pcall(function()local Root=GetRoot()if Root then local boss=nil local maxH=0 for _,obj in pairs(WS:GetDescendants())do if obj:IsA("Humanoid")and obj.MaxHealth>1e6 and obj.Health>0 and obj.Parent:FindFirstChild("HumanoidRootPart")then local dist=(Root.Position-obj.Parent.HumanoidRootPart.Position).Magnitude if dist<100 then boss=obj.Parent.HumanoidRootPart maxH=obj.MaxHealth break end end end if boss then Root.CFrame=boss.CFrame*CFrame.new(0,5,0)-- Focus kill end end end)wait(0.1)end end)print("Auto Boss: "..tostring(Togs.AutoBoss))end)
local IY=Instance.new("TextButton")IY.Size=UDim2.new(1,-20,0,40)IY.Position=UDim2.new(0,10,0.98,60)IY.BackgroundColor3=Color3.fromRGB(255,100,0)IY.Text="IY" IY.TextColor3=Color3.new(1,1,1)IY.Font=Enum.Font.GothamBold IY.TextScaled=true IY.Parent=Frm
IY.Activated:Connect(function()loadstring(game:HttpGet("https://raw.githubusercontent.com/EdgeIY/infiniteyield/master/source?v=1"))()end)
Cls.Activated:Connect(function()SG:Destroy()end)
print("¡v8 SECTORES AUTO! TP botón + Aura = Farm infinito por área. 💎")
